### ISSUE TITLE
GIT install using gow

### ISSUE THREAD

**Issue by circussocial** [bmatzelle/gow#105]
Can we have git as part of gow. It is simply the best thing on windows and it would be nice if we can make git and phing be part of it.

**Comment by imiric** [comment]
Apologies for reviving this old issue, but just wanted to comment for new wanderers that the [MSYS2](https://msys2.github.io/) project bundles MSYS with the excellent pacman, so installing Git (and many other packages) on Windows is now as simple as in Arch Linux: `pacman -Sy git`.

I was personally blown away by this fact recently, and decided to share. Cheers!
