### ISSUE TITLE
bash not executing .bat files

### ISSUE THREAD

**Issue by MatthewMiele** [bmatzelle/gow#153]
When trying to execute bat files such as ssh.bat it does not work.

When trying "ssh" I get
bash.exe": ssh: command not found

"ssh.bat"
bash.exe": /usr/bin/ssh.bat: No such file or directory

However running "ssh" from normal CMD works fine.

**Comment by ghost** [comment]
Matt, We're not talking about having bash parse batch files.  We're talking about bash knowing to execute the batch files using "cmd.exe /c <your batch file here>".  It clearly knows how to search the execution path for exe's, it should do the same for these.
