### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by lgordon** [bmatzelle/gow#16]
Although putty is a great ssh client for windows it doesn't seem to fit as well into this project as some of the other tools. I use putty all the time from the GUI but sometimes CLI usage are just more convenient. 

Couple things that just aren't quite right is lets say I do 

putty user@example.com, this will spawn the putty session in a new window. Is it possible to have it function more like ssh on *nix where the session will start in the same terminal window?

Also, I'm not sure if this is possible but with ssh on *nix if you don't specify a username when connecting to a client then your current account's user name is used. Can this be done as a default for Gow putty/ssh?

**Comment by Drugoy** [comment]
I don't know whether you are aware, but MS decided to maintain/adopt OpenSSH for windows by themselves, maybe their <a href="https://github.com/PowerShell/Win32-OpenSSH/releases">Win32-OpenSSH</a> should be used instead?

The quality of their util sucks yet, but seems like they are working hard on improving it.
