### ISSUE TITLE
Source for _GNU_ ported utilities

### ISSUE THREAD

**Issue by gilberterik** [bmatzelle/gow#164]
Links to source, compiliation instructions, build scripts and license need to be added to this repository.

**Comment by jethrocarr** [comment]
+1, this is a really useful collection but without source code and built tools, can never run or promote this as an option.

It's also not meeting the terms of the GNU license which require source to be distributed with binaries.

**Comment by bytehead-** [comment]
Correction.  Source needs to be available, not distributed.

Gow takes a bunch of other projects/utilities and creates an installation procedure and structure to implement them.

I agree that having links to the various projects would be nice, just to be able to update (or find an older version that doesn't have a feature broken) them without waiting for a new gow to come out with the new version.  With such a link of lists, adding other projects would become easier just by suggesting a link.

**Comment by bmatzelle** [comment]
Source code is included with releases.  See "gow-utilities-src-0.8.0.tar" link at the URL below.  

https://github.com/bmatzelle/gow/releases

**Comment by jethrocarr** [comment]
Ah OK the source is a separate tarball rather than in the Git repo where I was looking.  Are the build tools available anywhere, or do you unpack and build specific projects manually?

regards,
Jethro

**Comment by bmatzelle** [comment]
> Are the build tools available anywhere, or do you unpack and build specific projects manually?

They're built separately.  Many, such as Vim, are taken directly from the tested, official release binaries from the project web site.
