### ISSUE TITLE
Alternative SSH client?

### ISSUE THREAD

**Issue by loostro** [bmatzelle/gow#197]
Hi,

I'm used to linux or cygwin where I could put configuration in `.ssh/config` file and SSH would use it (wheather I try to connect with `ssh foobar` or I use a command that uses SSH `git clone ssh://foobar/baz.git`.

Now I've tried this project to replace Cygwin and It seems Plink does not read this configuration.

When I do `ssh foobar` I'm getting:

```console
Unable to open connection:
Host does not exist
```

Another (possibly related?) problem is when I try to build a vagrant box with `vagrant up` command. In the process of creation the guest machine is accessed via SSH. Previously (useing cygwin) I could build without problems. Now I'm getting:

```console
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

I am running a fresh Windows 8.1 64bit with latest Gow (0.8) installed.
Is there some way I could configure plink to look for `.ssh/config` file in my $HOME dir and use it?
Any ideas why vagrant can't connect via SSH (aka plink)?

**Comment by Stanzilla** [comment]
Quite possibly related, https://github.com/mitchellh/vagrant/issues/5997

I didn't even think about gow breaking that for me...

**Comment by loostro** [comment]
Is there any openssh windows client that I could use to replace plink?

I just realized problem no 1 can probably be fixed by copying the contents of `.ssh/config` into PuTTy (creating stored sessions)... but the problem with vagrant is a serious issue.

This (GOW) package is for power users, devs, etc and they will most likely use programs like vagrant, virtualbox, docker, .. Haveing an SSH client that can't use openssh keys could be a major issue to most GOW users.

**Comment by loostro** [comment]
Searching over internet I've found TTSSH client (under BSD License) so far. On their website they mention RSA keys support. Tomorrow I'll be testing if TTSSH could successfully replace plink.

**Comment by loostro** [comment]
WinSCP seems to have some basic SSH functionality (maybe it could be used?).

**Comment by loostro** [comment]
I've also found this... it might be the best. http://sshwindows.sourceforge.net/ It sais its `OpenSSH for Windows is a free package that installs a minimal OpenSSH server and client utilities in the Cygwin package without needing the full Cygwin installation.`

**Comment by loostro** [comment]
Ill test these tomorrow and share the results here.

**Comment by codex24** [comment]
@loostro, Do you have the scoop openssh package installed? It provides an
ssh client, but not server, and supersedes the implementation in gow.

On Tue, Aug 4, 2015 at 3:35 PM, loostro <notifications@github.com> wrote:

> Ill test these tomorrow and share the results here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bmatzelle/gow/issues/197#issuecomment-127753378>.
>



-- 
Opinions herein are exclusively my own, unless you share them.
Kevin Calman, codex24 at gmail dot com, Austin, TX, US

**Comment by Stanzilla** [comment]
@codex24 That worked for me. Remember to rename or delete the ssh.bat that comes with Gow though, so it won't be found first.

**Comment by loostro** [comment]
@codex24 Thanks for suggestion. In Windows PowerShell 3.0 (run as administrator) I've installed [scoop](https://github.com/lukesampson/scoop) via `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')` command. 

Then I had to change the script execution policy via `set-executionpolicy remotesigned` command and run `scoop install openssh` to install scoop openssh client.

After doing that, I've reset the execution policy to default via `set-executionpolicy restricted` command.
Then I've renamed the `ssh.bat`, so it is not executed when I run ssh command.

Now, when I tried connecting via `ssh foobar` I'm still getting an error:

```console
> ssh foobar
ssh.exe": Could not resolve hostname arkana-wan: no address associated with name
```

And I'm still getting error on `vagrant up`:

```console
> vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 5780 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

I'm not sure the system is useing the correct ssh client. I'll investigate further.

**Comment by loostro** [comment]
```console
loostro@PLUTO ~
> ssh -V
OpenSSH_5.4p1, OpenSSL 1.0.0 29 Mar 2010

loostro@PLUTO ~
> which ssh
C:\Users\loostro\appdata\local\scoop\shims\ssh.EXE
```

It seems it is useing the scoop package.. I wonder why its not working. 
[This guide](https://github.com/lukesampson/scoop/wiki/SSH-on-Windows#customising-ssh-settings) sais it should respect my `.ssh/config` file.

**Comment by loostro** [comment]
@codex24 This is weird. `ssh foobar` does not work, but `git clone ssh://foobar/baz.git` works! So my `.ssh/config` file is loaded (and used) at least by git.. which should be useing the default ssh client (am I right?).

**Comment by loostro** [comment]
@codex24 OK, I figured it out :) Running `ssh -F C:\Users\loostro\.ssh\config foobar` is working. It seems git automatically adds the -F argument, while plain ssh command does not look for `.ssh/config` in users home directory.

So I changed the GOW `ssh.bat` to:

```console
@echo off
C:\Users\loostro\appdata\local\scoop\shims\ssh.EXE %1 %2 %3 %4 %5 %6 %7 %8 %9 -F C:\Users\loostro\.ssh\config
```

To always read my config :)

Problem 1 solved. Yet, vagrant still refuses to work =(

**Comment by loostro** [comment]
I've uninstalled scoop ssh client and switched to msysgit ssh client, it had the same problem with config, so in GOW I changed the `ssh.bat` to:

```console
@echo off
"C:\Program Files (x86)\GOW\bin\ssh.exe" %1 %2 %3 %4 %5 %6 %7 %8 %9 -F C:\Users\loostro\.ssh\config
```

**Comment by loostro** [comment]
@bmatzelle Vagrant problems are not ssh client dependant, so I will close this issue. However I suggest adding to readme some notice about "How to use msysgit ssh openssh client instead of plink?".

**Comment by loostro** [comment]
The problem with vagrant was fixed by removeing `.vagrant` directory and all keys in `puphpet/files/dot/ssh`. Probably the leftover files from previous attempts (with plink as ssh client) caused it.

Issue on vagrant [#6088](https://github.com/mitchellh/vagrant/issues/6088)

**Comment by loostro** [comment]
After building the vagrant machine, I could not `vagrant ssh` becouse I got `command-line line 0: missing argument.` error. I changed the `ssh.bat` in `C:\Program Files (x86)\Gow\bin` to this:

```bat
@echo off
"C:\Program Files (x86)\Git\bin\ssh.exe" %* -F C:\Users\loostro\.ssh\config
```

The `%*` simply passes all arguments. The `-F path\to\config` makes all my ssh commands use my config from user home directory.

**Comment by tracker1** [comment]
@loostro I'd suggest...

```
@echo off
"%ProgramFiles(x86)%\Git\bin\ssh.exe" %* -F "%USERPROFILE%\.ssh\config"
```

So that it should work with any user...

**Comment by loostro** [comment]
@tracker1 I do not plan letting anyone near my laptop, but thanks for the tip. In case I ever create another user I won't suprise myself.. "why you no working 111!!" :)
