### ISSUE TITLE
Purpose of GOW Utilities SRC??

### ISSUE THREAD

**Issue by SurAnand** [bmatzelle/gow#198]
Hi,

I am not sure if I can keep this question here. As a novice new to all things programming, I could not understand the purpose of [GOW utilities SRC tar ball](https://github.com/bmatzelle/gow/releases/download/v0.8.0/gow-utilities-src-0.8.0.tar), from the available [documentation](https://github.com/bmatzelle/gow/releases) on github page. 

Please give a hint on how to use this and for what. I installed GOW.exe since all I get to do with it on Windows is like using any other installer. It's easy. 

Thank you.

**Comment by shayneo-harmonic** [comment]
GOW is free software (Like open source, but with a more vigillant license). That means source code needs to be included or made available in an accessible manner. If you dont know what the source is for, you almost certainly dont need it! But what it does is to allow you is to modify the code for GOW, and perhaps contribute your own changes back.

For a better understanding of the thinking, google up information on the GNU project and the Free Software Federation.

**Comment by bmatzelle** [comment]
Thanks for the thoughtful response @shayneo-harmonic
