### ISSUE TITLE
How use DD to physicalaccess drive ?

### ISSUE THREAD

**Issue by KaleiRo** [bmatzelle/gow#231]
Hi,

I can't found a documentation to how use dd, i have a Win PE 10 and want to use dd to read/write on physical drive or partition.

Can you explain how to ?

```
it's not possible to use \\.\PHYSICALDRIVE0, dd say :
dd: openning '\\\\.\\PHYSCALDRIVE0': no such file or directory
```

i have escaped with double quotes and same problem.

Thanks :-)

**Comment by patrolez** [comment]
Hi,
I have the same issue.

I do not know how to access PhysicalDrive. I am starting to be convinced that GOW is not able to deal with "block" devices in MS Windows manner.

Best Regards

**Comment by KaleiRo** [comment]
No answer, no news since 2016, ... Greats !
