### ISSUE TITLE
There are no sources on how to build these GNU programs

### ISSUE THREAD

**Issue by gnusupport** [bmatzelle/gow#261]
After review, I can see that you have not provided sources for the GNU programs being distributed, please do so, that we may try building these programs ourselves.

Another issue is that you have placed Gow license which is then contradictory to GNU GPL license under which majority of these GNU programs are conveyed. That causes misconception on how the GNU software can be distributed. Please clarify.

**Comment by bmatzelle** [comment]
I did this years ago: https://github.com/bmatzelle/gow/releases
