### ISSUE TITLE
Your Wiki has probably been hacked

### ISSUE THREAD

**Issue by parg** [bmatzelle/gow#265]
User kirniko editted it to insert a download link to 

https://github.com/kirniko/SingleFile/releases/tag/v0.3.31

have a nice day

**Comment by dalehagglund** [comment]
Got bitten by it today. Not that it's worth much, but the link is now https: / / linkify . me / CXsvy6Q . It's also still going on, with a few people trying to revert the changes.

Without going through them in the detail, many of the malicious commits have the title "Updated Home (markdown)".

**Comment by bmatzelle** [comment]
I locked it down.  Thanks!
