### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by stereobooster** [bmatzelle/gow#28]

**Comment by roded** [comment]
Yup.

**Comment by cloudranger** [comment]
I too needed a portable version of gow as I have no admin rights on my work windows PC.

You cannot use the installer as it tries to access the registry, and you cannot edit the system PATH as that is protected too if you are not admin.  I think I have more or less sorted it with a couple of steps (seems to be running OK so far). These instructions assume you have somewhere on your cripped PC where you are allowed to run some exe files from. Up to you to locate such a place.

1. Download the zip package from github and store somewhere (I used C:\Tools\gow - this is effectively the root as far as gow bash will be concerned)

2. Unzip the file

3. In the same location as the bin folder, create a folder called etc (bash needs this - the zip file could have really contained this in advance to avoid this step !!!)

4. Create a file called bash.bat with the following (change the path to suit where you install)
set PATH=%PATH%;C:\Tools\gow\bin
bash.exe

5. Double click on bash.bat and voila!

**Comment by nitrocode** [comment]
@stereobooster why was this closed? A portable version would be very useful.

**Comment by bmatzelle** [comment]
@nitrocode Re-opened.  It sounds useful.  I'll see what I can do.

**Comment by pletnes** [comment]
A distant second best might be to make an MSI installer which can install as a non-admin user. There are both pros and cons, as usual.

**Comment by krishnoid** [comment]
I'd definitely appreciate a no-install version, similar to GnuWin32.

**Comment by tracker1** [comment]
Definitely useful... I have a `./bin/{OSNAME}` in my dropbox that I keep for various utils like this that I add to my user path... having an easy way to update that would be awesome.  I try to keep as much the same as possible between linux, windows and mac.

**Comment by fseraphine** [comment]
I definitely support this feature. Would it be so hard to distribute a zip archive of the binaries ?

After test, I can open the .exe with 7zip and extract the bin directory.

**Comment by stereobooster** [comment]
![22751378_6683531](https://user-images.githubusercontent.com/179534/191496405-66b18803-5670-4d7e-9252-e044cbc7f538.jpg)

Image by <a href="https://www.freepik.com/free-vector/flat-design-10-years-anniversary-birthday_22751378.htm#query=10%20years%20anniversary&position=35&from_view=keyword">Freepik</a>
