### ISSUE TITLE
Missing libiconv2.dll in the setup file version 0.6.0

### ISSUE THREAD

**Issue by vdchuyen** [bmatzelle/gow#58]
Hi, my OS is Windows 7 x86_64, I have to use the libiconv2.dll at http://sourceforge.net/projects/gnuwin32/files/make/3.81/make-3.81-dep.zip to get the binaries working.

Please update this library in the setup packages.

Thanks,

**Comment by ghost** [comment]
Hey. After installing Gow 0.6.1. do i have to restart?
