### ISSUE TITLE
chmod appears to do nothing on Windows XP

### ISSUE THREAD

**Issue by mercutiomontague** [bmatzelle/gow#7]
Hey Guys,

Repeated attempts to use any of the following:

> chmod a+x myfile.sh
> chmod o+x myfile.sh

appear to do nothing. The file continues to have perms of rw-rw-rw.  My filesystem is NTFS.

**Comment by ianchanning** [comment]
It's not working on my 64-bit Windows 7 machine either.

**Comment by bytehead-** [comment]
I'm not sure what attributes you can actually change.  It seems that the only thing that chmod will change on an NTFS is the w attribute anyway.

    c:\>chmod -v a-w HWiNFO64.INI
    mode of `HWiNFO64.INI' changed to 0444 (r--r--r--)
    
    c:\>attrib
    A            C:\BRYANQ4.rtf
    A    R       C:\HWiNFO64.INI
    A            C:\Look at this.txt
    A            C:\malware.txt
    A            C:\palm.grf
    A            C:\SeagateExpansion.ico
    
    c:\>chmod -v a-w HWiNFO64.INI
    mode of `HWiNFO64.INI' retained as 0444 (r--r--r--)
    
    c:\>chmod -v a+w HWiNFO64.INI
    mode of `HWiNFO64.INI' changed to 0666 (rw-rw-rw-)
    
    c:\>attrib
    A            C:\BRYANQ4.rtf
    A            C:\HWiNFO64.INI
    A            C:\Look at this.txt
    A            C:\malware.txt
    A            C:\palm.grf
    A            C:\SeagateExpansion.ico`
 
Octal seems to work (using the -v to verify what it is doing), but again, you can only change the file from read/write to read-only, even though it says that it has changed.  

And even changing w is only effective for user (u) or all (a).  g and o change nothing on the file.

This is probably an NTFS limitation more than anything else.  *ix file attributes, IIRC, are part of security, and flipping the NTFS bit for read-only/write has nothing to do with security.

**Comment by ianchanning** [comment]
If you switch the file extension to `.bat` or `.exe` then the file attributes change to be executable.
