### ISSUE TITLE
tar -z fails because fork is not implemented

### ISSUE THREAD

**Issue by sjackman** [bmatzelle/gow#94]
tar -z fails because fork is not implemented.

> $ tar zxf mingw-w64-v2.0.8.tar.gz
> tar: Cannot fork: Function not implemented
> tar: Error is not recoverable: exiting now
> $ gzip -cd mingw-w64-v2.0.8.tar.gz |tar x
> $

**Comment by Blu3wolf** [comment]
so, out of scope?

**Comment by rfay** [comment]
So a standard use case of tar is nonfunctional; but there are versions of tar that do work. I guess I don't understand the goals of gow if fundamental features of things don't work.

For others landing here I note that
```
gzip -dc db.tar.gz | tar -tf -
```
would be the answer with gow

**Comment by codesniffer13** [comment]
> For others landing here I note that
> 
> ```
> gzip -dc db.tar.gz | tar -tf -
> ```
> 
> would be the answer with gow

This functionally works, but be aware that if the file is missing, the error code is still '0' (which indicates success), due to tar.
